import os
import time
import torch
import numpy as np
from PIL import Image
from gradcam import GradCAM, smooth_gradcam, generate_gradcam
from models.resnet18_model import get_resnet18
from torchvision import transforms
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

# Simple PDF report exporter for one image

DATA_DIR = './dataset'
MODEL_PATH = './saved_models/best_resnet18.pth'
OUTPUT_DIR = './outputs/reports'

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])


def load_model():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = get_resnet18(num_classes=4).to(device)
    model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
    model.eval()
    return model, device


def save_image(img, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path)


def generate_report(image_path, out_folder=None, n_smooth=25):
    if out_folder is None:
        out_folder = OUTPUT_DIR
    os.makedirs(out_folder, exist_ok=True)

    model, device = load_model()
    target_layer = model.layer4[-1]
    grad_cam = GradCAM(model, target_layer)

    image = Image.open(image_path).convert('RGB')
    input_tensor = transform(image).unsqueeze(0).to(device)

    # Prediction
    with torch.no_grad():
        out = model(input_tensor)
        probs = torch.softmax(out, dim=1).cpu().numpy()[0]
        pred_idx = int(np.argmax(probs))
        classes = ['glioma','meningioma','notumor','pituitary']
        pred_class = classes[pred_idx]
        confidence = float(probs[pred_idx])

    # Standard Grad-CAM
    cam = grad_cam(input_tensor)
    # SmoothGrad CAM
    smooth_cam = smooth_gradcam(grad_cam, input_tensor, n_samples=n_smooth, stdev_spread=0.12, class_idx=pred_idx)

    # Create heatmaps and overlays
    import cv2
    orig = np.array(image.resize((224,224)))
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
    heatmap = np.float32(heatmap) / 255
    overlay = heatmap + np.float32(orig) / 255
    overlay = overlay / np.max(overlay)

    smooth_heatmap = cv2.applyColorMap(np.uint8(255 * smooth_cam), cv2.COLORMAP_JET)
    smooth_heatmap = np.float32(smooth_heatmap) / 255
    smooth_overlay = smooth_heatmap + np.float32(orig) / 255
    smooth_overlay = smooth_overlay / np.max(smooth_overlay)

    # Save images
    base = os.path.splitext(os.path.basename(image_path))[0]
    timestamp = int(time.time())
    orig_path = os.path.join(out_folder, f"{base}_{timestamp}_orig.png")
    heat_path = os.path.join(out_folder, f"{base}_{timestamp}_heat.png")
    overlay_path = os.path.join(out_folder, f"{base}_{timestamp}_overlay.png")
    smooth_heat_path = os.path.join(out_folder, f"{base}_{timestamp}_smooth_heat.png")
    smooth_overlay_path = os.path.join(out_folder, f"{base}_{timestamp}_smooth_overlay.png")

    Image.fromarray(orig).save(orig_path)
    Image.fromarray(np.uint8(255 * heatmap)).save(heat_path)
    Image.fromarray(np.uint8(255 * overlay)).save(overlay_path)
    Image.fromarray(np.uint8(255 * smooth_heatmap)).save(smooth_heat_path)
    Image.fromarray(np.uint8(255 * smooth_overlay)).save(smooth_overlay_path)

    # Create PDF
    pdf_path = os.path.join(out_folder, f"{base}_{timestamp}_report.pdf")
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, height - 50, "Brain Tumor Detection Report")

    # Prediction summary
    c.setFont("Helvetica", 12)
    c.drawString(40, height - 80, f"Image: {os.path.basename(image_path)}")
    c.drawString(40, height - 100, f"Predicted class: {pred_class}")
    c.drawString(40, height - 120, f"Confidence: {confidence*100:.2f}%")

    # Insert images
    x = 40
    y = height - 420
    img_w = 240
    img_h = 240

    c.drawString(x, y + img_h + 10, "Original")
    c.drawImage(ImageReader(orig_path), x, y, width=img_w, height=img_h)

    c.drawString(x + img_w + 30, y + img_h + 10, "Grad-CAM Heatmap")
    c.drawImage(ImageReader(heat_path), x + img_w + 30, y, width=img_w, height=img_h)

    c.drawString(x, y - img_h - 20, "Overlay")
    c.drawImage(ImageReader(overlay_path), x, y - img_h - 40, width=img_w, height=img_h)

    c.drawString(x + img_w + 30, y - img_h - 20, "SmoothGrad Overlay")
    c.drawImage(ImageReader(smooth_overlay_path), x + img_w + 30, y - img_h - 40, width=img_w, height=img_h)

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(40, 30, "Generated by Brain Tumor Detection pipeline")

    c.save()

    print(f"Report saved to: {pdf_path}")
    return pdf_path


if __name__ == '__main__':
    # CLI usage: python export_report.py path/to/image.jpg
    import sys
    if len(sys.argv) > 1:
        img_path = sys.argv[1]
    else:
        img_path = 'dataset/glioma/Tr-pi_955.jpg'

    if os.path.exists(img_path) and os.path.exists(MODEL_PATH):
        generate_report(img_path)
    else:
        print('Provide a valid image path and ensure model checkpoint exists at', MODEL_PATH)
